#LANGUAGE CLASSFICATION
DEFAULT_LANGUAGE = 1 # Current default language is Korean.
ENGLISH = 0
KOREAN = 1
ESPANOL = 2

"""ACTION TASKS"""
UNKNOWN_ERROR = -1
GREETING = 0
COVID = 1
BRIGHTNESS = 2
VOLUME = 3
CLOCK = 4
TIMER = 5
JOKE = 6

HOUSE_PARTY_PROTOCOL = 999